baseURL = 'https://gitorko.github.io/'
languageCode = 'en-us'
title = 'GitOrko'
copyright = ""

paginate = 10
theme = ["hugo-clarity", "hugo-notice"]
[services]
    [services.disqus]
        shortname = "gitorko"
enableRobotsTXT = true

enableEmoji = true

DefaultContentLanguage = "en"

[mediaTypes."application/javascript"]
suffixes = ["ts","js","jsm","mjs"]

[taxonomies]
category = "categories"
tag = "tags"

[outputs]
home = ["HTML", "RSS", "JSON"]
